FROM python:3.11-slim

USER root
# 1. Actualizamos el SO y las herramientas base de Python inmediatamente
RUN apt-get update && apt-get upgrade -y && \
    pip install --no-cache-dir --upgrade pip setuptools wheel && \
    rm -rf /var/lib/apt/lists/*
    
# Creamos un grupo y un usuario sin privilegios
# Usamos un ID fijo (1000) para facilitar la configuración en K8s
RUN groupadd -g 1000 ekumen && \
    useradd -u 1000 -g ekumen -m -s /bin/bash ekumen_user

WORKDIR /app

# Copiamos los archivos asegurando que el nuevo usuario sea el dueño (--chown)
COPY --chown=ekumen_user:ekumen deploy_dist/saludo/ /app/saludo/

# Damos permisos de ejecución al binario
RUN chmod +x /app/saludo/app_saludo

# Cambiamos el contexto de ejecución al usuario no-root
USER ekumen_user

# Ejecutamos el binario
CMD ["sh", "-c", "/app/saludo/app_saludo && tail -f /dev/null"]