# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-saludo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-saludo
  template:
    metadata:
      labels:
        app: app-saludo
    spec:
      # Configuración de seguridad a nivel de Pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: saludo-container
        image: sriveraloaiza/saludo-ekumen:dd516ec61f0600bb5f971da5613411cee974c0f5
        ports:
        - containerPort: 80
          name: http-app
        - containerPort: 8000  # <--- Nuevo puerto para métricas
          name: metrics
        # Configuración de seguridad a nivel de Contenedor
        securityContext:
          # Evita que el proceso gane más privilegios de los iniciales
          allowPrivilegeEscalation: false
          # Bloquea el disco: no se pueden crear ni modificar archivos
          readOnlyRootFilesystem: true
          # Elimina capacidades del kernel innecesarias (net_raw, etc.)
          capabilities:
            drop:
              - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: saludo-service
  labels:            # <--- AGREGA ESTO
    app: app-saludo
spec:
  selector:
    app: app-saludo
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics  # <--- Nuevo puerto en el Service
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP