# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-saludo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-saludo
  template:
    metadata:
      labels:
        app: app-saludo
    spec:
      # Configuración de seguridad a nivel de Pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: saludo-container
        image: sriveraloaiza/saludo-ekumen:7aaa4d57b375dfd7a097aa9a3b9ef43386972f5b
        ports:
        - containerPort: 80
          name: http-app
        - containerPort: 8000  # <--- Nuevo puerto para métricas
          name: metrics
        # Configuración de seguridad a nivel de Contenedor
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: saludo-service
  labels:            # <--- AGREGA ESTO
    app: app-saludo
spec:
  selector:
    app: app-saludo
  ports:
    - name: http-app
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics  # <--- Nuevo puerto en el Service
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP