apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-saludo-monitor
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: app-saludo
  endpoints:
  - port: metrics 
    interval: 15s