name: CI/CD Pipeline

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permite al bot hacer push al repositorio
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # Usamos una acción oficial para instalar Bazel
      - name: Instalar Bazelisk (Bazel)
        run: |
          sudo curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
          bazel --version # Verificación rápida

      - name: Compilar con Bazel
        run: |
          bazel build //saludo:app_saludo
          # Preparamos la carpeta de distribución igual que hicimos manualmente
          mkdir -p deploy_dist/saludo
          cp $(bazel info bazel-bin)/saludo/app_saludo ./deploy_dist/saludo/
          cp -RL $(bazel info bazel-bin)/saludo/app_saludo.runfiles ./deploy_dist/saludo/

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          # Usamos el hash del commit como tag para que cada imagen sea única
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/saludo-ekumen:latest
            ${{ secrets.DOCKER_USERNAME }}/saludo-ekumen:${{ github.sha }}

      # Añade esto después del paso de 'Construir y subir imagen'
      - name: Actualizar manifiesto de K8s
        run: |
          # Extraemos el tag corto del commit
          IMAGE_TAG=${{ github.sha }}
          # Usamos sed para cambiar la imagen en el archivo deployment.yaml
          # Asegúrate de que la ruta 'k8s/deployment.yaml' sea la correcta en tu repo
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/saludo-ekumen:$IMAGE_TAG|g" k8s/deployment.yaml
          
      - name: Commit y Push del cambio en el YAML
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "chore: update image tag to ${{ github.sha }} [skip ci]"
          git push